### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by stymbhrdwj** [VOLMAP/volmap.github.io#1]
I am unable to download the dataset from the links provided on the github page. The server does not respond. I want to download the files `G1.zip` through `G6.zip`.

**Comment by gcherchi** [comment]
Hi,
I tried it right now and it works :) Maybe there was a temporary problem.

**Comment by stymbhrdwj** [comment]
I tried using a VPN and it worked. Thanks for checking.

**Comment by mlivesu** [comment]
Hi, this is weird. I've tried from two different computers and internet connections and all downloads seem to work properly. 
The only thing that comes to my mind is that zip files are big, so depending on your connection/bandwidth you may encounter a timeout
